export const lightTheme = {
  mode: 'light',
  STATUS_BAR: 'light_content',
  PRIMARY_BACKGROUND_COLOR: '#ffffff',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#ddd',
  SECONDARY_BACKGROUND_COLOR: '#1F3B4D',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#999999',

  PRIMARY_TEXT_COLOR: '#017374',
  SECONDARY_TEXT_COLOR: '#D0FEFE',
  TERTIARY_TEXT_COLOR: '#1F3B4D',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#1F3B4D',
};

export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#000000',
  PRIMARY_BACKGROUND_COLOR_LIGHT: '#797979',
  SECONDARY_BACKGROUND_COLOR: '#182936',
  SECONDARY_BACKGROUND_COLOR_LIGHT: '#dddddd',

  PRIMARY_TEXT_COLOR: '#ffffff',
  SECONDARY_TEXT_COLOR: '#ffffff',
  TERTIARY_TEXT_COLOR: '#D0FEFE',
  PRIMARY_TEXT_BACKGROUND_COLOR: '#3d3d3d',
  SECONDARY_TEXT_BACKGROUND_COLOR: '#000000',
};
